apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: myweb
spec:
  replicas: 5
  selector:
     matchLabels:
       app: myweb
  template:
   metadata:
     labels:
        app: myweb
   spec:
     containers:
     - name: myweb
       image: kubeguide/tomcat-app:v1
       ports:
       - containerPort: 8080
       env:
       - name: MYSQL_SERVICE_HOST
         value: 'mysql'
       - name: MYSQL_SERVICE_PORT
         value: '3306'    
