apiVersion: v1
kind: Service
metadata:
  name: nginx-web
  labels:
    tier: frontend
spec:
  type: NodePort
  selector:
    tier: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
     tier: frontend 
  template:
    metadata:
      labels:
        tier: frontend
    spec:
     containers:
     - name: nginx
       image: nginx
       ports:
       - name: http
         containerPort: 80
