apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels: 
    name: frontend
spec:
  replicas: 3
  selector:
    matchLabels: 
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
     containers:
     - name: frontend
       image: kubeguide/guestbook-php-frontend
       env:
       - name: GET_HOST_FROM
         value: env
       ports:
       - containerPort: 80
