apiVersion: apps/v1
kind: Deployment
metadata:
 name: redis-slave
 labels:
   name: redis-slave
spec:
 replicas: 2
 selector:
   matchLabels:
      name: redis-slave
 template:
   metadata:
     labels:
        name: redis-slave
   spec:
     containers:
     - name: master
       image: kubeguide/guestbook-redis-slave
       env:
       - name: GET_HOSTS_FROM
         value: env
       ports:
       - containerPort: 6379
