apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: doudou-read-pods
  name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-read
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: doudou
