apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
     app: myapp-hpa
  template:
    metadata:
      labels:
        app: myapp-hpa
    spec:
     containers:
     - name: myapp
       image: ikubernetes/metrics-app
       ports:
       - name: http
         containerPort: 80 
 

