apiVersion: v1
kind: Pod
metadata:
 name: pod-first
 namespace: default
 labels:
  app: myapp
  tier: frontend
 annotations:
  doudou/create-by: "cluster admin"
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
---
apiVersion: v1
kind: Pod
metadata:
 name: pod-second
 labels:
  app: backend
  tier: db
spec:
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    command: [ "sh","-c","sleep 3600"] 
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - {key: app , operator: In , values: ["myapp"]}
        topologyKey: zone
