apiVersion: v1
kind: Pod
metadata:
 name: pod-affinity1 
 namespace: default
 labels:
  app: myapp
  tier: frontend
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
           - key: zone
             operator: In
             values:
             - foo
             - bar
        weight: 60  
