apiVersion: v1
kind: Pod
metadata:
 name: pod-demo
 namespace: default
 labels:
  app: myapp
  tier: frontend
 annotations:
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
  nodeSelector:
    disktype: harddisk
