apiVersion: v1
kind: Pod
metadata:
  name: pod-nfs
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1 
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: html
    nfs:
     path: /data/volumes
     server: k8s-master
